export enum LegendaryEnum {
    UNKNOW = 0,
    AUDACE_DE_DODGE = 1,
    CEINTURE_DE_DAME_JHESSICA = 2,
    BOTTES_DU_CUL_BOTTE = 3,
    BOTTES_DE_MILLE_LIEUES = 4,
    COURONNE_DE_BRAM_BARBE_MONDE = 5,
    DIADEME_DE_GANYMEDE = 6,
    BRAVOURE_DE_RYKKE_ERREL = 7,
    CAPE_DE_JAHASH_JURGEN = 8,
    TROMPE_LA_MORT = 9,
    DROITURE_DE_FALLANSTER = 10,
    PLUME_DE_BUHORADO = 11,
    CROCOBUR = 12
}