export enum PacketEnum {
    CHECK = 0,
    PROTOCOL_REQUIRED = 1,
    NETWORK_DATA_CONTAINER = 2,
    HELLO_CONNECT = 3,
    IDENTIFICATION = 4,
    CHARACTER_CHARACTERISTICS_INFOS = 8,
    LOGIN_QUEUE_STATUS = 10,
    IDENTIFICATION_FAILED = 20,
    IDENTIFICATION_FAILED_FOR_BAD_VERSION = 21,
    IDENTIFICATION_SUCCESS = 22,
    GAME_SERVER_INFOS = 25,
    SERVERS_LIST = 30,
    SERVER_SELECTION = 40,
    SELECTED_SERVER_REFUSED = 41,
    SELECTED_SERVER_DATA = 42,
    SPELL_ITEM = 49,
    SERVER_STATUS_UPDATE = 50,
    STARTUP_ACTION_ADD_OBJECT  = 52,
    ENTITY_MOVEMENT_INFOS = 63,
    CONSOLE = 75,
    ADMIN_COMMAND = 76,
    CHARACTER_HARDCORE_INFOS = 86,
    TAX_COLLECTOR_BASIC_INFOS = 96,

    BASIC_NO_OPERATION = 176,

    CURRENT_MAP = 220,

    MAP_INFOS_REQUEST = 225,

    CHAT_SERVER = 881,
    CHAT_SERVER_COPY_MESSAGE = 882,
    CHAT_SERVER_WITH_OBJECT = 883,

    GAME_MAP_MOVEMENT_REQUEST = 950,
    GAME_MAP_MOVEMENT = 951,
    GAME_MAP_MOVEMENT_CONFIRM = 952,
    
    BASIC_ACK = 6362
}