import { PacketMessage } from "../controllers/PacketMessage";
import { Packet } from "../models/packets/Packet";
import { ChatServerMessage } from "../controllers/messages/ChatServerMessage";
import { ChatServerWithObjectMessage } from "../controllers/messages/ChatServerWithObjectMessage";
import { GameMapMovementMessage } from "../controllers/messages/GameMapMovementMessage";
import { GameMapMovementConfirmMessage } from "../controllers/messages/GameMapMovementConfirmMessage";
import { GameMapMovementRequestMessage } from "../controllers/messages/GameMapMovementRequestMessage";
import { GameActionAcknowledgementMessage } from "../controllers/messages/GameActionAcknowledgementMessage";
import { GameContextRemoveElementMessage } from "../controllers/messages/GameContextRemoveElementMessage";
import { GameRolePlayAttackMonsterRequestMessage } from "../controllers/messages/GameRolePlayAttackMonsterRequestMessage";
import { GameFightTurnEndMessage } from "../controllers/messages/GameFightTurnEndMessage";
import { GameFightTurnReadyMessage } from "../controllers/messages/GameFightTurnReadyMessage";
import { BasicNoOperationMessage } from "../controllers/messages/BasicNoOperationMessage";
import { BasicPongMessage } from "../controllers/messages/BasicPongMessage";
import { BasicPingMessage } from "../controllers/messages/BasicPingMessage";
import { InventoryWeightMessage } from "../controllers/messages/InventoryWeightMessage";
import { SequenceEndMessage } from "../controllers/messages/SequenceEndMessage";
import { CharacterLevelUpMessage } from "../controllers/messages/CharacterLevelUpMessage";
import { GameContextDestroyMessage } from "../controllers/messages/GameContextDestroyMessage";
import { GameContextCreateMessage } from "../controllers/messages/GameContextCreateMessage";
import { LifePointsRegenBeginMessage } from "../controllers/messages/LifePointsRegenBeginMessage";
import { LifePointsRegenEndMessage } from "../controllers/messages/LifePointsRegenEndMessage";
import { MapInformationsRequestMessage } from "../controllers/messages/MapInformationsRequestMessage";
import { SequenceNumberRequestMessage } from "../controllers/messages/SequenceNumberRequestMessage";
import { SequenceNumberMessage } from "../controllers/messages/SequenceNumberMessage";
import { BasicLatencyStatsRequestMessage } from "../controllers/messages/BasicLatencyStatsRequestMessage";
import { BasicLatencyStatsMessage } from "../controllers/messages/BasicLatencyStatsMessage";
import { GameFightOptionStateUpdateMessage } from "../controllers/messages/GameFightOptionStateUpdateMessage";
import { ChallengeResultMessage } from "../controllers/messages/ChallengeResultMessage";
import { CharacterStatsListMessage } from "../controllers/messages/CharacterStatsListMessage";
import { ChannelEnablingMessage } from "../controllers/messages/ChannelEnablingMessage";
import { ChannelEnablingChangeMessage } from "../controllers/messages/ChannelEnablingChangeMessage";
import { GuildGetInfosMessage } from "../controllers/messages/GuildGetInfosMessage";
import { ProtocolRequired } from "../controllers/messages/ProtocolRequired";
import { ReloginTokenStatusMessage } from "../controllers/messages/ReloginTokenStatusMessage";
import { ReloginTokenStatusRequestMessage } from "../controllers/messages/ReloginTokenStatusRequestMessage";
import { HelloGameMessage } from "../controllers/messages/HelloGameMessage";
import { AuthenticationTicketMessage } from "../controllers/messages/AuthenticationTicketMessage";
import { AuthenticationTicketAcceptedMessage } from "../controllers/messages/AuthenticationTicketAcceptedMessage";
import { RawDataMessage } from "../controllers/messages/RawDataMessage";
import { BasicTimeMessage } from "../controllers/messages/BasicTimeMessage";
import { QueueStatusMessage } from "../controllers/messages/QueueStatusMessage";
import { CheckIntegrityRequestMessage } from "../controllers/messages/CheckIntegrityRequestMessage";
import { ServerSettingsMessage } from "../controllers/messages/ServerSettingsMessage";
import { AccountCapabilitiesMessage } from "../controllers/messages/AccountCapabilitiesMessage";
import { ServerSessionConstantsMessage } from "../controllers/messages/ServerSessionConstantsMessage";
import { TrustStatusMessage } from "../controllers/messages/TrustStatusMessage";
import { ServerOptionalFeaturesMessage } from "../controllers/messages/ServerOptionalFeaturesMessage";
import { CharactersListRequestMessage } from "../controllers/messages/CharactersListRequestMessage";
import { CharactersListMessage } from "../controllers/messages/CharactersListMessage";
import { GameFightTurnFinishMessage } from "../controllers/messages/GameFightTurnFinishMessage";
import { ObjectAveragePricesGetMessage } from "../controllers/messages/ObjectAveragePricesGetMessage";
import { QuestListRequestMessage } from "../controllers/messages/QuestListRequestMessage";
import { QuestListMessage } from "../controllers/messages/QuestListMessage";
import { GuildInfosPaddocksMessage } from "../controllers/messages/GuildInfosPaddocksMessage";
import { NetworkDataContainerMessage } from "../controllers/messages/NetworkDataContainerMessage";
import { FriendsListMessage } from "../controllers/messages/FriendsListMessage";
import { TextInfosMessage } from "../controllers/messages/TextInfosMessage";
import { CurrentMapMessage } from "../controllers/messages/CurrentMapMessage";
import { EmotePlayRequestMessage } from "../controllers/messages/EmotePlayRequestMessage";
import { UpdateMapPlayersAggressableStatusMessage } from "../controllers/messages/UpdateMapPlayersAggressableStatusMessage";
import { CharacterSelectionMessage } from "../controllers/messages/CharacterSelectionMessage";
import { CharacterSelectionSuccessMessage } from "../controllers/messages/CharacterSelectionSuccessMessage";
import { NotificationListMessage } from "../controllers/messages/NotificationListMessage";
import { SpellListMessage } from "../controllers/messages/SpellListMessage";
import { GameFightStartingMessage } from "../controllers/messages/GameFightStartingMessage";
import { GameFightJoinRequestMessage } from "../controllers/messages/GameFightJoinRequestMessage";
import { GameFightJoinMessage } from "../controllers/messages/GameFightJoinMessage";
import { GameFightPlacementPossiblePositionsMessage } from "../controllers/messages/GameFightPlacementPossiblePositionsMessage";
import { GameFightPlacementPositionRequestMessage } from "../controllers/messages/GameFightPlacementPositionRequestMessage";
import { MapComplementaryInfosDataMessage } from "../controllers/messages/MapComplementaryInfosDataMessage";
import { GameEntitiesDispositionMessage } from "../controllers/messages/GameEntitiesDispositionMessage";
import { GameFightUpdateTeamMessage } from "../controllers/messages/GameFightUpdateTeamMessage";
import { GameFightShowFighterMessage } from "../controllers/messages/GameFightShowFighterMessage";
import { GameFightReadyMessage } from "../controllers/messages/GameFightReadyMessage";
import { GameFightStartMessage } from "../controllers/messages/GameFightStartMessage";
import { GameFightTurnListMessage } from "../controllers/messages/GameFightTurnListMessage";
import { GameFightTurnStartMessage } from "../controllers/messages/GameFightTurnStartMessage";
import { GameFightTurnReadyRequestMessage } from "../controllers/messages/GameFightTurnReadyRequestMessage";
import { GameFightHumanReadyStateMessage } from "../controllers/messages/GameFightHumanReadyStateMessage";
import { GameFightEndMessage } from "../controllers/messages/GameFightEndMessage";
import { CharacterExperienceGainMessage } from "../controllers/messages/CharacterExperienceGainMessage";
import { SetCharacterRestrictionsMessage } from "../controllers/messages/SetCharacterRestrictionsMessage";
import { FighterStatsListMessage } from "../controllers/messages/FighterStatsListMessage";
import { ChallengeInfosMessage } from "../controllers/messages/ChallengeInfosMessage";
import { GameFightTurnStartPlayingMessage } from "../controllers/messages/GameFightTurnStartPlayingMessage";
import { AbstractGameActionMessage } from "../controllers/messages/AbstractGameActionMessage";
import { GameActionFightPointsVariationMessage } from "../controllers/messages/GameActionFightPointsVariationMessage";
import { PlayerStatusUpdateMessage } from "../controllers/messages/PlayerStatusUpdateMessage";
import { SequenceStartMessage } from "../controllers/messages/SequenceStartMessage";
import { GameFightSynchronizeMessage } from "../controllers/messages/GameFightSynchronizeMessage";
import { GameFightNewRoundMessage } from "../controllers/messages/GameFightNewRoundMessage";
import { GameRolePlayShowActorMessage } from "../controllers/messages/GameRolePlayShowActorMessage";
import { IdolFightPreparationUpdateMessage } from "../controllers/messages/IdolFightPreparationUpdateMessage";
import { AbstractGameActionFightTargetedAbilityMessage } from "../controllers/messages/AbstractGameActionFightTargetedAbilityMessage";
import { GameActionFightSpellCastMessage } from "../controllers/messages/GameActionFightSpellCastMessage";
import { GameActionFightCastRequestMessage } from "../controllers/messages/GameActionFightCastRequestMessage";
import { GameActionFightDispellableEffectMessage } from "../controllers/messages/GameActionFightDispellableEffectMessage";
import { GameActionFightLifePointsLostMessage } from "../controllers/messages/GameActionFightLifePointsLostMessage";
import { GameActionFightLifeAndShieldPointsLostMessage } from "../controllers/messages/GameActionFightLifeAndShieldPointsLostMessage";
import { GameActionFightSummonMessage } from "../controllers/messages/GameActionFightSummonMessage";
import { GameActionFightLifePointsGainMessage } from "../controllers/messages/GameActionFightLifePointsGainMessage";
import { GameActionFightDeathMessage } from "../controllers/messages/GameActionFightDeathMessage";
import { GameActionFightSlideMessage } from "../controllers/messages/GameActionFightSlideMessage";
import { AchievementListMessage } from "../controllers/messages/AchievementListMessage";
import { GameActionFightCloseCombatMessage } from "../controllers/messages/GameActionFightCloseCombatMessage";
import { GameActionFightReduceDamagesMessage } from "../controllers/messages/GameActionFightReduceDamagesMessage";
import { GameActionFightTeleportOnSameMapMessage } from "../controllers/messages/GameActionFightTeleportOnSameMapMessage";
import { GameActionFightExchangePositionsMessage } from "../controllers/messages/GameActionFightExchangePositionsMessage";
import { GameActionFightDispellMessage } from "../controllers/messages/GameActionFightDispellMessage";
import { GameActionFightDispellSpellMessage } from "../controllers/messages/GameActionFightDispellSpellMessage";
import { GameActionFightInvisibilityMessage } from "../controllers/messages/GameActionFightInvisibilityMessage";
import { GameActionFightInvisibleDetectedMessage } from "../controllers/messages/GameActionFightInvisibleDetectedMessage";
import { GameActionFightDispellEffectMessage } from "../controllers/messages/GameActionFightDispellEffectMessage";
import { GameActionFightTackledMessage } from "../controllers/messages/GameActionFightTackledMessage";
import { GameFightRefreshFighterMessage } from "../controllers/messages/GameFightRefreshFighterMessage";
import { GameActionFightTriggerGlyphTrapMessage } from "../controllers/messages/GameActionFightTriggerGlyphTrapMessage";
import { GameActionFightUnmarkCellsMessage } from "../controllers/messages/GameActionFightUnmarkCellsMessage";
import { GameActionFightMarkCellsMessage } from "../controllers/messages/GameActionFightMarkCellsMessage";
import { GameActionFightDodgePointLossMessage } from "../controllers/messages/GameActionFightDodgePointLossMessage";

class PacketManager {
    public packets: typeof PacketMessage[];

    constructor() {
        this.packets = new Array();
        /*this.packets[1] = ProtocolRequired;
        this.packets[2] = NetworkDataContainerMessage;
        // this.packets[3] = HelloConnectMessage;
        // this.packets[4] = IdentificationMessage;
        // this.packets[10] = LoginQueueStatusMessage;
        // this.packets[20] = IdentificationFailedMessage;
        // this.packets[21] = IdentificationFailedForBadVersionMessage;
        // this.packets[22] = IdentificationSuccessMessage;
        // this.packets[30] = ServersListMessage;
        // this.packets[40] = ServerSelectionMessage;
        // this.packets[41] = SelectedServerRefusedMessage;
        // this.packets[42] = SelectedServerDataMessage;
        // this.packets[50] = ServerStatusUpdateMessage;
        // this.packets[75] = ConsoleMessage;
        // this.packets[76] = AdminConsoleMessage;
        // this.packets[76] = AdminConsoleMessage;
        this.packets[101] = HelloGameMessage;
        // this.packets[109] = AlreadyConnectMessage;
        this.packets[110] = AuthenticationTicketMessage;
        this.packets[111] = AuthenticationTicketAcceptedMessage;
        // this.packets[112] = AuthenticationTicketRefusedMessage;
        this.packets[150] = CharactersListRequestMessage;
        this.packets[151] = CharactersListMessage;
        this.packets[152] = CharacterSelectionMessage;
        this.packets[153] = CharacterSelectionSuccessMessage;
        // this.packets[160] = CharacterCreationRequestMessage;
        // this.packets[161] = CharacterCreationResultMessage;
        // this.packets[162] = CharacterNameSuggestionRequestMessage;
        // this.packets[164] = CharacterNameSuggestionFailureMessage;
        // this.packets[165] = CharacterDeletionRequestMessage;
        // this.packets[166] = CharacterDeletionErrorMessage;
        // this.packets[167] = CharacterReplayRequestMessage;
        this.packets[170] = SetCharacterRestrictionsMessage;
        this.packets[175] = BasicTimeMessage;
        this.packets[176] = BasicNoOperationMessage;
        // this.packets[177] = BasicDateMessage;
        // this.packets[179] = BasicWhoIsNoMatchMessage;
        // this.packets[180] = BasicWhoIsMessage;
        // this.packets[181] = BasicWhoIsRequestMessage;
        this.packets[182] = BasicPingMessage;
        this.packets[183] = BasicPongMessage;
        //this.packets[189] = SystemMessageDisplayMessage;
        this.packets[200] = GameContextCreateMessage;
        this.packets[201] = GameContextDestroyMessage;*/
        this.packets[220] = CurrentMapMessage;
        /*this.packets[225] = MapInformationsRequestMessage;
        this.packets[226] = MapComplementaryInfosDataMessage;
        //this.packets[250] = GameContextCreateRequestMessage;
        this.packets[251] = GameContextRemoveElementMessage;*/
        // this.packets[500] = CharacterStatsListMessage;
        this.packets[700] = GameFightStartingMessage;
        //this.packets[701] = GameFightJoinRequestMessage;
        //this.packets[702] = GameFightJoinMessage;
        this.packets[703] = GameFightPlacementPossiblePositionsMessage;
        //this.packets[704] = GameFightPlacementPositionRequestMessage;
        //this.packets[708] = GameFightReadyMessage;
        this.packets[712] = GameFightStartMessage;
        this.packets[713] = GameFightTurnListMessage;
        this.packets[714] = GameFightTurnStartMessage;
        this.packets[715] = GameFightTurnReadyRequestMessage;
        //this.packets[716] = GameFightTurnReadyMessage;
        //this.packets[718] = GameFightTurnFinishMessage;
        this.packets[719] = GameFightTurnEndMessage;
        this.packets[720] = GameFightEndMessage;
        /*this.packets[740] = GameFightHumanReadyStateMessage;
        this.packets[780] = TextInfosMessage;
        this.packets[881] = ChatServerMessage;
        this.packets[883] = ChatServerWithObjectMessage;
        this.packets[890] = ChannelEnablingMessage;
        this.packets[891] = ChannelEnablingChangeMessage;
        //this.packets[892] = EnabledChannelsMessage;
        this.packets[950] = GameMapMovementRequestMessage;*/
        this.packets[951] = GameMapMovementMessage;
        // this.packets[952] = GameMapMovementConfirmMessage;
        this.packets[955] = SequenceStartMessage;
        this.packets[956] = SequenceEndMessage;
        /*this.packets[957] = GameActionAcknowledgementMessage;
        this.packets[1000] = AbstractGameActionMessage;*/
        this.packets[1004] = GameActionFightTackledMessage;
        // this.packets[1005] = GameActionFightCastRequestMessage;
        this.packets[1010] = GameActionFightSpellCastMessage;
        this.packets[1030] = GameActionFightPointsVariationMessage;
        this.packets[1099] = GameActionFightDeathMessage;
        /*this.packets[1200] = SpellListMessage;
        this.packets[3009] = InventoryWeightMessage;
        //this.packets[3016] = InventoryContentMessage;
        //this.packets[4001] = FriendsGetListMessage;
        this.packets[4002] = FriendsListMessage;*/
        this.packets[5525] = GameActionFightSlideMessage;
        this.packets[5526] = GameActionFightReduceDamagesMessage;
        this.packets[5527] = GameActionFightExchangePositionsMessage;
        this.packets[5528] = GameActionFightTeleportOnSameMapMessage;
        this.packets[5533] = GameActionFightDispellMessage;
        this.packets[5540] = GameActionFightMarkCellsMessage;
        /*this.packets[5550] = GuildGetInfosMessage;*/
        this.packets[5570] = GameActionFightUnmarkCellsMessage;
        /*this.packets[5572] = GameFightUpdateTeamMessage;
        //this.packets[5607] = ClientKeyMessage;
        this.packets[5623] = QuestListRequestMessage;
        this.packets[5626] = QuestListMessage;
        //this.packets[5630] = FriendWarnOnConnectionStateMessage;
        //this.packets[5632]= GameRolePlayShowActorMessage;
        //this.packets[5652] = JobCrafterDirectorySettingsMessage;
        //this.packets[5655] = JobDescriptionMessage;
        this.packets[5663] = BasicLatencyStatsMessage;
        this.packets[5670] = CharacterLevelUpMessage;
        //this.packets[5676] = IgnoredGetListMessage;
        this.packets[5684] = LifePointsRegenBeginMessage;
        this.packets[5685] = EmotePlayRequestMessage;
        this.packets[5686] = LifePointsRegenEndMessage;
        //this.packets[5689] = EmoteListMessage;*/
        this.packets[5696] = GameEntitiesDispositionMessage;
        /* //this.packets[5708] = InteractiveElementUpdatedMessage;
        //this.packets[5709] = StatedElementUpdatedMessage;*/
        this.packets[5741] = GameActionFightTriggerGlyphTrapMessage;
        /*this.packets[5809] = JobExperienceMultiUpdateMessage;
        this.packets[5816] = BasicLatencyStatsRequestMessage;*/
        this.packets[5821] = GameActionFightInvisibilityMessage;
        this.packets[5825] = GameActionFightSummonMessage;
        this.packets[5828] = GameActionFightDodgePointLossMessage;
        this.packets[5864] = GameFightShowFighterMessage;
        /*this.packets[5921] = GameFightSynchronizeMessage;
        this.packets[5927] = GameFightOptionStateUpdateMessage;
        this.packets[5959] = GuildInfosPaddocksMessage;
        this.packets[6019] = ChallengeResultMessage;
        this.packets[6022] = ChallengeInfosMessage;
        this.packets[6058] = AlignmentRankUpdateMessage;*/
        this.packets[6070] = GameActionFightDispellableEffectMessage;
        /*this.packets[6078] = FriendWarnOnLevelGainStateMessage;
        this.packets[6087] = NotificationListMessage;
        this.packets[6100] = QueueStatusMessage;*/
        this.packets[6113] = GameActionFightDispellEffectMessage;
        this.packets[6116] = GameActionFightCloseCombatMessage;
        /*this.packets[6118] = AbstractGameActionFightTargetedAbilityMessage;
        //this.packets[6160] = GuildMemberWarnOnConnectionStateMessage;*/
        this.packets[6176] = GameActionFightDispellSpellMessage;
        //this.packets[6191] = GameRolePlayAttackMonsterRequestMessage;
        //this.packets[6205] = AchievementListMessage;
        /*this.packets[6216] = AccountCapabilitiesMessage;
        //this.packets[6231] = ShortcutBarContentMessage;
        //this.packets[6237] = ServerExperienceModificatorMessage;*/
        this.packets[6239] = GameFightNewRoundMessage;
        /*this.packets[6253] = RawDataMessage;
        //this.packets[6265] = SpouseStatusMessage;
        this.packets[6267] = TrustStatusMessage;
        this.packets[6305] = ServerOptionalFeaturesMessage;*/
        this.packets[6309] = GameFightRefreshFighterMessage;
        this.packets[6310] = GameActionFightLifeAndShieldPointsLostMessage;
        this.packets[6311] = GameActionFightLifePointsGainMessage;
        this.packets[6312] = GameActionFightLifePointsLostMessage;
        /*this.packets[6316] = SequenceNumberRequestMessage;
        this.packets[6317] = SequenceNumberMessage;*/
        this.packets[6320] = GameActionFightInvisibleDetectedMessage;
        //this.packets[6321] = CharacterExperienceGainMessage;
        this.packets[6322] = FighterStatsListMessage;
        /*this.packets[6334] = ObjectAveragePricesGetMessage;
        this.packets[6340] = ServerSettingsMessage;
        //this.packets[6355] = SpouseGetInformationsMessage;
        this.packets[6372] = CheckIntegrityRequestMessage;
        //this.packets[6383] = FriendGuildWarnOnAchievementCompleteStateMessage;
        this.packets[6386] = PlayerStatusUpdateMessage;
        this.packets[6434] = ServerSessionConstantsMessage;
        //this.packets[6440] = PrismsListMessage;
        this.packets[6454] = UpdateMapPlayersAggressableStatusMessage;
        this.packets[6465] = GameFightTurnStartPlayingMessage;
        //this.packets[6513] = WarnOnPermaDeathStateMessage;
        this.packets[6539] = ReloginTokenStatusMessage;
        this.packets[6540] = ReloginTokenStatusRequestMessage;
        this.packets[6586] = IdolFightPreparationUpdateMessage;*/
    }

    public analyze(packetId: number, packet: Packet): PacketMessage {
        let packetMessage: PacketMessage;
        let packetClass: typeof PacketMessage = this.packets[packetId];
        if(packetClass) {
            packetMessage = new packetClass();
            packetMessage.analyze(packet);
        }

        return packetMessage;
    }
}

export const packetManager = new PacketManager();
