INSERT INTO Challenge
    (id, name)
VALUES
    (1, "Zombie"),
    (2, "Statue"),
    (3, "Premier"),
    (4, "Dernier"),
    (5, "Économe"),
    (6, "Versatile"),
    (7, "Jardinier"),
    (8, "Nomade"),
    (9, "Barbare"),
    (10, "Désordonné"),
    (11, "Mystique"),
    (12, "Fossoyeur"),
    (13, "Casino royal"),
    (15, "Araknophile"),
    (17, "Intouchable"),
    (18, "Incurable"),
    (19, "Mains propres"),
    (20, "Élémentaire"),
    (21, "Circulez"),
    (22, "Le temps qui court"),
    (23, "Perdu de vue"),
    (24, "Borné"),
    (25, "Ordonné"),
    (28, "Ni pioutes ni soumises"),
    (29, "Ni pious ni soumis"),
    (30, "Les petits d'abord"),
    (31, "Focus"),
    (32, "Élitiste"),
    (33, "Survivant"),
    (34, "Imprévisible"),
    (35, "Tueur à gages"),
    (36, "Hardi"),
    (37, "Collant"),
    (38, "Blitzkrieg"),
    (39, "Anachorète"),
    (40, "Pussilanime"),
    (41, "Pétulant"),
    (42, "Deux pour le prix d'un"),
    (43, "Abnégation"),
    (44, "Partage"),
    (45, "Duel"),
    (46, "Chacun son monstre"),
    (47, "Contamination"),
    (48, "Les mules d'abord"),
    (50, "Le cheat des dev's");