INSERT INTO Emoticon
    (id,name)
VALUES
    (1, "S'asseoir"),
    (2, "Faire un signe de la main"),
    (3, "Applaudir"),
    (4, "Se mettre en colère"),
    (5, "Montrer sa peur"),
    (6, "Montrer son arme"),
    (7, "Flûte"),
    (8, "Lâcher les gaz"),
    (9, "Saluer"),
    (10, "Faire un bisou"),
    (11, "Pierre"),
    (12, "Feuille"),
    (13, "Ciseau"),
    (14, "Croiser les bras"),
    (15, "Pointer du doigt"),
    (16, "Corbeau"),
    (19, "S'allonger"),
    (21, "Champion"),
    (22, "Aura de puissance"),
    (23, "Aura vampyrique"),
    (24, "Rire"),
    (25, "Refuser"),
    (26, "Pleurer"),
    (27, "Danser"),
    (28, "Jouer de la guitare"),
    (29, "Jongler"),
    (30, "Lire un livre"),
    (32, "Joie"),
    (33, "Trace"),
    (34, "Mains sur les hanches"),
    (35, "Offrir des fleurs"),
    (36, "Etre frigorifié"),
    (37, "Eternuer"),
    (38, "Manolia"),
    (39, "Avoir froid"),
    (40, " "),
    (41, "Bailler"),
    (42, "Sautiller"),
    (43, "Lever le pouce"),
    (44, "Baisser le pouce"),
    (45, "Jouer du tambour"),
    (46, "Affamé"),
    (47, "Etre touché"),
    (48, "Faire le piou"),
    (49, "Faire coucou"),
    (50, "Jouer aux cartes"),
    (51, "Super Héros"),
    (52, "Supplier"),
    (53, "Jouer de la trompette"),
    (54, "Jouer de la harpe"),
    (55, "Aura de Nelween"),
    (56, "Offrir un cadeau"),
    (57, "Téméraire"),
    (58, "S'agenouiller"),
    (59, "Faire le poirier"),
    (62, " "),
    (63, "Lézard"),
    (64, "Spock"),
    (65, "Salut Vulcain"),
    (66, "Se prosterner"),
    (67, "Avoir chaud"),
    (68, "Gonfler ses muscles"),
    (69, "Lire une carte"),
    (70, "Ogrine"),
    (71, "Poing levé"),
    (72, "Pied de nez"),
    (73, "Attirer l'attention"),
    (74, "Motus"),
    (75, "Se frotter les mains"),
    (76, "Faire un facepaume"),
    (77, "Garde à vous"),
    (78, "Ola"),
    (79, "Se frapper le front"),
    (80, "Mains derrière le dos"),
    (81, "Kamarena"),
    (82, "Siffler"),
    (83, " "),
    (84, "Longue vue"),
    (85, "Loupe"),
    (86, " "),
    (87, "Huer"),
    (88, "Encourager"),
    (89, "Se boucher les oreilles"),
    (90, "Halouine"),
    (92, "Ecrire"),
    (93, "Défourailler son arme"),
    (94, "Tirer la langue"),
    (95, "Kramouflage"),
    (96, "Brandir son bouclier"),
    (97, "Etendard de guilde"),
    (98, "Etendard d'alliance"),
    (99, "Sablier de la Clepsydre"),
    (101, "Croquer une cawotte"),
    (102, " "),
    (103, "Offrir un gâteau"),
    (104, "Roboculaire"),
    (105, "Boxer"),
    (106, "Drapeau blanc"),
    (107, "Cracheur de feu"),
    (108, "S'envoler"),
    (109, "Ver de terre"),
    (110, "Phorrer le sol"),
    (111, "Renifler le sol"),
    (112, "Chercheur de trésor"),
    (113, "Localiser un portail"),
    (114, "Ouvrir un portail de poche"),
    (117, "Richissime"),
    (118, "Rugir"),
    (119, "Criminelle"),
    (120, "Explosive"),
    (121, "Intemporelle"),
    (122, "Transcendant"),
    (123, "Hanter"),
    (124, "Se dandiner"),
    (125, "Piétiner"),
    (126, "Enflammer"),
    (127, "Se protéger"),
    (128, "Peindre"),
    (129, "Sylvestre"),
    (130, "Colère de Bolgrot"),
    (132, "Vaporeuse"),
    (133, "Parasol"),
    (134, "Pecher"),
    (135, "Balistique"),
    (136, " "),
    (137, "Elémentaire"),
    (138, "Krosmoz"),
    (139, "Déployer ses ailes bontariennes"),
    (140, "Déployer ses ailes brakmariennes"),
    (141, "Pile ou face"),
    (142, "Chanceux"),
    (143, "Sanguinolente"),
    (144, "Bienfaisant"),
    (146, "Psychotique"),
    (147, "Animal"),
    (148, "Indestructible"),
    (149, "Gonfler un ballon"),
    (150, "Expérimenter"),
    (152, "Enragé"),
    (153, " "),
    (154, " "),
    (155, "Clash of Guilds"),
    (156, "DOFUS Cup"),
    (158, " "),
    (159, " "),
    (160, " "),
    (163, " "),
    (166, " "),
    (167, " "),
    (168, " "),
    (169, " "),
    (170, " "),
    (171, " "),
    (172, " "),
    (173, " "),
    (174, " "),
    (175, " "),
    (176, "Millenium"),
    (177, "Gamers Origins"),
    (178, "Batailleurs Glorieux"),
    (179, "Free Bowisse"),
    (180, "Out Of Control"),
    (181, "Dofus Ivoire"),
    (182, "Dofus Ebène"),
    (183, "Dofus Emeraude"),
    (184, "Dofus Turquoise"),
    (185, "Dofus Ocre"),
    (186, "Dofus Pourpre"),
    (189, " "),
    (190, "Out Of Control"),
    (191, "Gamers Origins"),
    (192, "Millenium"),
    (193, "Batailleurs Glorieux"),
    (194, "OV");