INSERT INTO Mount
    (id, name)
VALUES
    (1, "Dragodinde Amande Sauvage"),
    (3, "Dragodinde Ebène"),
    (6, "Dragodinde Rousse Sauvage"),
    (9, "Dragodinde Ebène et Ivoire"),
    (10, "Dragodinde Rousse"),
    (11, "Dragodinde Ivoire et Rousse"),
    (12, "Dragodinde Ebène et Rousse"),
    (15, "Dragodinde Turquoise"),
    (16, "Dragodinde Ivoire"),
    (17, "Dragodinde Indigo"),
    (18, "Dragodinde Dorée"),
    (19, "Dragodinde Pourpre"),
    (20, "Dragodinde Amande"),
    (21, "Dragodinde Emeraude"),
    (22, "Dragodinde Orchidée"),
    (23, "Dragodinde Prune"),
    (33, "Dragodinde Amande et Dorée"),
    (34, "Dragodinde Amande et Ebène"),
    (35, "Dragodinde Amande et Emeraude"),
    (36, "Dragodinde Amande et Indigo"),
    (37, "Dragodinde Amande et Ivoire"),
    (38, "Dragodinde Amande et Rousse"),
    (39, "Dragodinde Amande et Turquoise"),
    (40, "Dragodinde Amande et Orchidée"),
    (41, "Dragodinde Amande et Pourpre"),
    (42, "Dragodinde Dorée et Ebène"),
    (43, "Dragodinde Dorée et Emeraude"),
    (44, "Dragodinde Dorée et Indigo"),
    (45, "Dragodinde Dorée et Ivoire"),
    (46, "Dragodinde Dorée et Rousse"),
    (47, "Dragodinde Dorée et Turquoise"),
    (48, "Dragodinde Dorée et Orchidée"),
    (49, "Dragodinde Dorée et Pourpre"),
    (50, "Dragodinde Ebène et Emeraude"),
    (51, "Dragodinde Ebène et Indigo"),
    (52, "Dragodinde Ebène et Turquoise"),
    (53, "Dragodinde Ebène et Orchidée"),
    (54, "Dragodinde Ebène et Pourpre"),
    (55, "Dragodinde Emeraude et Indigo"),
    (56, "Dragodinde Emeraude et Ivoire"),
    (57, "Dragodinde Emeraude et Rousse"),
    (58, "Dragodinde Emeraude et Turquoise"),
    (59, "Dragodinde Emeraude et Orchidée"),
    (60, "Dragodinde Emeraude et Pourpre"),
    (61, "Dragodinde Indigo et Ivoire"),
    (62, "Dragodinde Indigo et Rousse"),
    (63, "Dragodinde Indigo et Turquoise"),
    (64, "Dragodinde Indigo et Orchidée"),
    (65, "Dragodinde Indigo et Pourpre"),
    (66, "Dragodinde Ivoire et Turquoise"),
    (67, "Dragodinde Ivoire et Orchidée"),
    (68, "Dragodinde Ivoire et Pourpre"),
    (69, "Dragodinde Turquoise et Rousse"),
    (70, "Dragodinde Orchidée et Rousse"),
    (71, "Dragodinde Pourpre et Rousse"),
    (72, "Dragodinde Turquoise et Orchidée"),
    (73, "Dragodinde Turquoise et Pourpre"),
    (74, "Dragodinde Dorée Sauvage"),
    (76, "Dragodinde Orchidée et Pourpre"),
    (77, "Dragodinde Prune et Amande"),
    (78, "Dragodinde Prune et Dorée"),
    (79, "Dragodinde Prune et Ebène"),
    (80, "Dragodinde Prune et Emeraude"),
    (82, "Dragodinde Prune et Indigo"),
    (83, "Dragodinde Prune et Ivoire"),
    (84, "Dragodinde Prune et Rousse"),
    (85, "Dragodinde Prune et Turquoise"),
    (86, "Dragodinde Prune et Orchidée"),
    (87, "Dragodinde Prune et Pourpre"),
    (88, "Dragodinde en armure"),
    (89, "Dragodinde à Plumes"),
    (90, "Muldo Orchidée"),
    (91, "Muldo Ebène"),
    (92, "Muldo Indigo"),
    (93, "Muldo Pourpre"),
    (94, "Muldo Doré"),
    (95, "Muldo Roux"),
    (96, "Muldo Amande"),
    (97, "Muldo Ivoire"),
    (98, "Muldo Turquoise"),
    (99, "Muldo Prune"),
    (100, "Muldo Emeraude"),
    (101, "Muldo Doré et Pourpre"),
    (102, "Muldo Indigo et Pourpre"),
    (103, "Muldo Ebène et Pourpre"),
    (104, "Muldo Orchidée et Pourpre"),
    (105, "Muldo Doré et Orchidée"),
    (106, "Muldo Indigo et Orchidée"),
    (107, "Muldo Ebène et Orchidée"),
    (108, "Muldo Doré et Indigo"),
    (109, "Muldo Ebène et Indigo"),
    (110, "Muldo Doré et Ebène"),
    (111, "Muldo Roux et Pourpre"),
    (112, "Muldo Roux et Orchidée"),
    (113, "Muldo Roux et Indigo"),
    (114, "Muldo Roux et Ebène"),
    (115, "Muldo Roux et Doré"),
    (116, "Muldo Roux et Amande"),
    (117, "Muldo Pourpre et Amande"),
    (118, "Muldo Orchidée et Amande"),
    (119, "Muldo Indigo et Amande"),
    (120, "Muldo Ebène et Amande"),
    (121, "Muldo Doré et Amande"),
    (122, "Muldo Pourpre et Ivoire"),
    (123, "Muldo Orchidée et Ivoire"),
    (124, "Muldo Indigo et Ivoire"),
    (125, "Muldo Ebène et Ivoire"),
    (126, "Muldo Doré et Ivoire"),
    (127, "Muldo Roux et Ivoire"),
    (138, "Muldo Amande et Ivoire"),
    (139, "Muldo Turquoise et Ivoire"),
    (140, "Muldo Turquoise et Pourpre"),
    (141, "Muldo Turquoise et Indigo"),
    (142, "Muldo Turquoise et Ebène"),
    (143, "Muldo Turquoise et Roux"),
    (144, "Muldo Turquoise et Amande"),
    (145, "Muldo Turquoise et Doré"),
    (146, "Muldo Prune et Pourpre"),
    (147, "Muldo Prune et Orchidée"),
    (148, "Muldo Prune et Indigo"),
    (149, "Muldo Prune et Ebène"),
    (150, "Muldo Prune et Doré"),
    (151, "Muldo Prune et Roux"),
    (152, "Muldo Prune et Amande"),
    (153, "Muldo Prune et Ivoire"),
    (154, "Muldo Prune et Turquoise"),
    (155, "Muldo Prune et Emeraude"),
    (156, "Muldo Pourpre et Emeraude"),
    (157, "Muldo Orchidée et Emeraude"),
    (158, "Muldo Indigo et Emeraude"),
    (159, "Muldo Ebène et Emeraude"),
    (160, "Muldo Doré et Emeraude"),
    (161, "Muldo Roux et Emeraude"),
    (162, "Muldo Amande et Emeraude"),
    (163, "Muldo Ivoire et Emeraude"),
    (164, "Muldo Turquoise et Emeraude"),
    (165, "Muldo Turquoise et Orchidée"),
    (167, "Muldo Doré Sauvage"),
    (168, "Muldo Pourpre Sauvage"),
    (169, "Muldo Indigo Sauvage"),
    (170, "Muldo Ebène Sauvage"),
    (171, "Muldo Orchidée Sauvage"),
    (172, "Volkorne Pourpre Sauvage"),
    (173, "Volkorne Orchidée Sauvage"),
    (174, "Volkorne Indigo Sauvage"),
    (175, "Volkorne Ebène Sauvage"),
    (176, "Volkorne Indigo"),
    (177, "Volkorne Ebène"),
    (178, "Volkorne Pourpre"),
    (179, "Volkorne Orchidée"),
    (180, "Volkorne Roux"),
    (181, "Volkorne Amande"),
    (182, "Volkorne Ivoire"),
    (183, "Volkorne Turquoise"),
    (184, "Volkorne Prune"),
    (185, "Volkorne Emeraude"),
    (186, "Volkorne Doré"),
    (187, "Volkorne Jade"),
    (188, "Volkorne Rubis"),
    (189, "Volkorne Saphir"),
    (190, "Volkorne Améthyste"),
    (191, "Volkorne Pourpre et Orchidée"),
    (192, "Volkorne Pourpre et Indigo"),
    (193, "Volkorne Pourpre et Ebène"),
    (194, "Volkorne Orchidée et Indigo"),
    (195, "Volkorne Orchidée et Ebène"),
    (196, "Volkorne Indigo et Ebène"),
    (197, "Volkorne Amande et Pourpre"),
    (198, "Volkorne Amande et Orchidée"),
    (199, "Volkorne Amande et Indigo"),
    (200, "Volkorne Amande et Ebène"),
    (201, "Volkorne Amande et Roux"),
    (202, "Volkorne Amande et Ivoire"),
    (203, "Volkorne Amande et Turquoise"),
    (204, "Volkorne Roux et Pourpre"),
    (205, "Volkorne Roux et Orchidée"),
    (206, "Volkorne Roux et Indigo"),
    (207, "Volkorne Roux et Ebène"),
    (208, "Volkorne Roux et Ivoire"),
    (209, "Volkorne Roux et Turquoise"),
    (210, "Volkorne Ivoire et Pourpre"),
    (211, "Volkorne Ivoire et Orchidée"),
    (212, "Volkorne Ivoire et Indigo"),
    (213, "Volkorne Ivoire et Ebène"),
    (214, "Volkorne Ivoire et Turquoise"),
    (215, "Volkorne Turquoise et Pourpre"),
    (216, "Volkorne Turquoise et Orchidée"),
    (217, "Volkorne Turquoise et Indigo"),
    (218, "Volkorne Turquoise et Ebène"),
    (219, "Volkorne Prune et Pourpre"),
    (220, "Volkorne Prune et Orchidée"),
    (221, "Volkorne Prune et Indigo"),
    (222, "Volkorne Prune et Ebène"),
    (223, "Volkorne Prune et Amande"),
    (224, "Volkorne Prune et Turquoise"),
    (225, "Volkorne Prune et Emeraude"),
    (226, "Volkorne Emeraude et Pourpre"),
    (227, "Volkorne Emeraude et Orchidée"),
    (228, "Volkorne Emeraude et Indigo"),
    (229, "Volkorne Emeraude et Ebène"),
    (230, "Volkorne Emeraude et Amande"),
    (231, "Volkorne Emeraude et Roux"),
    (233, "Volkorne Emeraude et Ivoire"),
    (234, "Volkorne Emeraude et Turquoise"),
    (235, "Volkorne Doré et Pourpre"),
    (236, "Volkorne Doré et Orchidée"),
    (237, "Volkorne Doré et Indigo"),
    (238, "Volkorne Doré et Ebène"),
    (239, "Volkorne Jade et Pourpre"),
    (240, "Volkorne Jade et Orchidée"),
    (241, "Volkorne Jade et Indigo"),
    (242, "Volkorne Jade et Ebène"),
    (243, "Volkorne Jade et Amande"),
    (244, "Volkorne Jade et Roux"),
    (245, "Volkorne Jade et Ivoire"),
    (246, "Volkorne Jade et Turquoise"),
    (247, "Volkorne Jade et Prune"),
    (248, "Volkorne Jade et Emeraude"),
    (249, "Volkorne Jade et Doré"),
    (250, "Volkorne Jade et Rubis"),
    (251, "Volkorne Jade et Saphir"),
    (252, "Volkorne Jade et Améthyste"),
    (253, "Volkorne Rubis et Pourpre"),
    (254, "Volkorne Rubis et Orchidée"),
    (255, "Volkorne Rubis et Indigo"),
    (256, "Volkorne Rubis et Ebène"),
    (257, "Volkorne Rubis et Amande"),
    (258, "Volkorne Rubis et Roux"),
    (259, "Volkorne Rubis et Ivoire"),
    (260, "Volkorne Rubis et Turquoise"),
    (261, "Volkorne Rubis et Prune"),
    (262, "Volkorne Rubis et Emeraude"),
    (263, "Volkorne Rubis et Doré"),
    (264, "Volkorne Saphir et Pourpre"),
    (265, "Volkorne Saphir et Orchidée"),
    (266, "Volkorne Saphir et Indigo"),
    (267, "Volkorne Saphir et Ebène"),
    (268, "Volkorne Saphir et Amande"),
    (269, "Volkorne Saphir et Roux"),
    (270, "Volkorne Saphir et Ivoire"),
    (271, "Volkorne Saphir et Turquoise"),
    (272, "Volkorne Saphir et Prune"),
    (273, "Volkorne Saphir et Emeraude"),
    (274, "Volkorne Saphir et Doré"),
    (275, "Volkorne Saphir et Améthyste"),
    (276, "Volkorne Améthyste et Pourpre"),
    (277, "Volkorne Améthyste et Orchidée"),
    (278, "Volkorne Améthyste et Indigo"),
    (279, "Volkorne Améthyste et Ebène"),
    (280, "Volkorne Améthyste et Amande"),
    (281, "Volkorne Améthyste et Roux"),
    (282, "Volkorne Améthyste et Ivoire"),
    (283, "Volkorne Améthyste et Turquoise"),
    (284, "Volkorne Améthyste et Prune"),
    (285, "Volkorne Améthyste et Emeraude"),
    (286, "Volkorne Améthyste et Doré"),
    (287, "Volkorne Prune et Roux"),
    (288, "Volkorne Prune et Ivoire"),
    (289, "Volkorne Rubis et Saphir"),
    (290, "Volkorne Rubis et Améthyste"),
    (291, "Volkorne Doré et Roux"),
    (292, "Volkorne Doré et Amande"),
    (293, "Volkorne Doré et Ivoire"),
    (294, "Volkorne Doré et Turquoise"),
    (295, "Volkorne Doré et Prune"),
    (296, "Volkorne Doré et Emeraude");